### ISSUE TITLE
cuDNN error: CUDNN_STATUS_NOT_INITIALIZED in Execute the experiment, in _conv_forward()

### ISSUE THREAD

**Issue by ZGX010** [BonifazStuhr/feamgan#3]
I found a problem when following the readme to predict the pre-trained model (Prediction\Execute the experiment)

`
docker run -it --rm --gpus device=0 --cpus 64 --shm-size=32G --ipc=host -v E:\feamgan:/root/feamgan -w /root/feamgan feamgan_docker python -u -m feamgan.main`
`

experimentSchedule.json
`
{
  "mode": "sequential",
  "experimentsToRun": ["InferenceExperiment"],
  "experimentConfigsToRun": {"InferenceExperiment": [
    "pretrainedModels/val/FeaMGAN_Viper_to_Cityscapes_Crop352_Full.json"
    ]}
}
`

Log: 
`
/opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [148,0,0], thread: [58,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [148,0,0], thread: [59,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [148,0,0], thread: [60,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [148,0,0], thread: [61,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [148,0,0], thread: [62,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1634272168290/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:276: operator(): block: [148,0,0], thread: [63,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "/root/feamgan/feamgan/Experiment_Component/Experiments/InferenceExperiment.py", line 86, in execute
    trainValInferModel(model_config, model_dir, dataset_config, self.__local_rank, world_size, self.__num_threads, self.__seed, self.__use_wandb)
  File "/root/feamgan/feamgan/Experiment_Component/Experiments/experimentFunctions.py", line 160, in trainValInferModel
    model_suit.doInference("eval")
  File "/root/feamgan/feamgan/Experiment_Component/AModelSuit.py", line 542, in doInference
    gen_pred = self._model.module.inference(data)
  File "/root/feamgan/feamgan/Experiment_Component/Models/FeaMGAN.py", line 266, in inference
    fake_image_batch = self.generateFake(content_g, None)
  File "/root/feamgan/feamgan/Experiment_Component/Models/FeaMGAN.py", line 452, in generateFake
    fake_image = self.netG(input_semantics, real_image)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/feamgan/feamgan/Experiment_Component/Models/Backbones/Generators/FeaMGenerator.py", line 49, in forward
    ft0, ft1, ft2, ft3, ft4, ft5, ft6, ft7 = self.content_stream(input)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/feamgan/feamgan/Experiment_Component/Models/Streams/Stream.py", line 29, in forward
    input = self.act(self.linear_0(input))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

terminate called after throwing an instance of 'dali::CUDAError'
  what():  CUDA runtime API error cudaErrorAssert (710):
device-side assert triggered
`

**Comment by ZGX010** [comment]
NVIDIA-SMI 535.54.04              Driver Version: 536.23       CUDA Version: 12.2

**Comment by ZGX010** [comment]
nvcc --version
`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
Build cuda_11.3.r11.3/compiler.29920130_0
`

**Comment by ZGX010** [comment]
Is this problem due to the need to resize the training data? The current data size is not 935*526

**Comment by ZGX010** [comment]
This is due to me forgetting the conversion step；

format the segmentations of the dataset to grayscale
